### ISSUE TITLE
Installing PyAudio for py3.5 into Blender's python distribution

### ISSUE THREAD

**Issue by zeffii** [nomelif/Audionodes#1]
i'm using the Python compiled with Blender, and win10 64bit

all i did was a `python -m pip install pyaudio` , into my local Python installation.
Then copied these (or their *nix equivalent) files over into blender's _python/lib/site-packages_

```
python/lib/site-packages/PyAudio-0.2.9.dist-info/..
python/lib/site-packages/_portaudio.cp35-win_amd64.pyd
python/lib/site-packages/pyaudio.py
```

**Comment by nomelif** [comment]
This actually works?! I have been engineering mad science including patching pip into a live python with exec.

**Comment by nomelif** [comment]
Also, python/lib/site-packages (to my understanding) isn't writable with Blender installed as admin on Windozes. Am I right with that?

**Comment by zeffii** [comment]
i've never installed Blender with an installer, I use the portable zip and launch with a shortcut, but unless the  user has the site-packages inside `ProgramFiles`, there should be no barrier to adding files to the Blender provided `python/lib/site-packages` directory.

**Comment by nomelif** [comment]
That is precisely where it is located. `C:\Program Files\Blender Foundation\Blender\2.78\python\lib\site-packages` to be exact.

**Comment by zeffii** [comment]
yikes.. of course it is ;(

**Comment by nomelif** [comment]
Ok, I consistently get this in my VM:

<a href="http://imgur.com/IYBm6w9"><img src="http://i.imgur.com/IYBm6w9.png" title="source: imgur.com" /></a>

(Installed throuhg pip in a native install of python 3.5, copied over)

**Comment by zeffii** [comment]
ok, then on windows PyGame and PyAudio can be injected temporarily into sys,path. Wherever the user has their py35 distribution with those modules

```python
import sys
local_py35_packages = r'C:\Users\zeffi\Anaconda3\Lib\site-packages`
if not local_py35_packages in sys.path:
    sys.path.append(local_py35_packages)

import pygame
import pyaudio
```

**Comment by nomelif** [comment]
That was what I was working on before. That seemed to function indeed, but orchestrating the baroque waltz of `msi` installers, `pip` installs and digging up of the paths takes some time. That also has the benefit of solving the writability problems.

**Comment by nomelif** [comment]
On the flip side:

![image](https://cloud.githubusercontent.com/assets/6322311/20795297/178d864c-b7d9-11e6-88c6-a44e4e7f3c57.png)

I thought that worked. The os is a naked win 7 vm snapshotted on first boot. Installed Python and Blender, then installed pygame via pip.

The install worked out fine and everything seemed OK:

![image](https://cloud.githubusercontent.com/assets/6322311/20795348/62eebebc-b7d9-11e6-8fb7-d429622a798a.png)

**Comment by nomelif** [comment]
My personal guess: Blender runs cp 3.5.1 and the installed python is cp 3.5.2. I will attempt to install cp 3.5.1, but that sounds quite far-fetched.

**Comment by zeffii** [comment]
I would not be surprised _at all_ if that was the problem. mismatch dll versions...

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20795807/695e1d34-b7d3-11e6-9011-8105a409b61e.png)

**Comment by nomelif** [comment]
What standalone python are you running?

**Comment by zeffii** [comment]
from anaconda3  64bit  

```
C:\Program Files (x86)>python
Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

```

**Comment by nomelif** [comment]
Wait? The thing works across 3.5.1 / 3.5.2 and CP / Anaconda?! DLL -problems don't really seem likely.

**Comment by zeffii** [comment]
and : http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame   precompiled..

**Comment by zeffii** [comment]
hope this isn't bogging you down, I think it should be up to the users to get the right version during early development, and lateron take more time to figure out easy installs.

**Comment by nomelif** [comment]
Pip on 3.5.1 fails to find pygame at all.

Well, if I can't set up the thing by hand, I guess having it work is a high priority.

**Comment by zeffii** [comment]
that's the pain of adding dependencies. thanks be to the blendergods that numpy _is_ included :)

**Comment by nomelif** [comment]
Yep. Though including pip wouldn't hurt too much.

**Comment by zeffii** [comment]
the pain is also a reason why [we](https://github.com/nortikin/sverchok) (sverchok) don't include any 3rd party stuff yet. hassle.

**Comment by nomelif** [comment]
Well, we are kind of cornered with sound-related stuff. `Aud` only lets you play an audio file written to disk by path as a string. Performance would be... interesting.

**Comment by nomelif** [comment]
The compiled package you pointed to:

![image](https://cloud.githubusercontent.com/assets/6322311/20796291/41ba3924-b7de-11e6-97fd-efeb35eea158.png)

Whatever that means, 32bit windows vm with 32 bit python 3.5.1

**Comment by zeffii** [comment]
and you win7 version is what?   32 bit ? are you sure? :)

**Comment by nomelif** [comment]
![image](https://cloud.githubusercontent.com/assets/6322311/20796396/9806312a-b7de-11e6-8c72-e1905a900865.png)

Pretty sure.

Would making a proposal for the inclusion of pip in Blender proper make sense? Getting numpy in was the fruit of such an action.

**Comment by zeffii** [comment]
oh.. ` >>>   wmic os get osarchitecture ` 
```
C:\Users\zeffi>wmic os get osarchitecture
OSArchitecture
64-bit

```

**Comment by zeffii** [comment]
can you install win32's python 3.5 anaconda on that image ?

**Comment by nomelif** [comment]
I am going to be afk for about 30min. I will try the Anaconda if you deem it useful. Also, is this a problem inherent to win32? I would be more than happy to drop it like a hot rock if that is what is needed.

**Comment by zeffii** [comment]
drop win32.   can't support everything for everyone forever.

**Comment by nomelif** [comment]
Ok, I am back. I will try to set up a x86_64 vm.

**Comment by nomelif** [comment]
I will give win10 a try.

**Comment by nomelif** [comment]
By

> Also, is this a problem inherent to win32?

I mean 32-bit windows, not the Python module.
