### ISSUE TITLE
Got output :)

### ISSUE THREAD

**Issue by zeffii** [nomelif/Audionodes#2]
![image](https://cloud.githubusercontent.com/assets/619340/20789281/fbda1c3c-b7b3-11e6-92b3-30291353f1cc.png)

**Comment by zeffii** [comment]
I can only speak for Windows, and might experience problems that you don't when using a POSIX system like osx or linux.

The output can be disconnected abruptly, when you leave the focus of Blender's window. I'm suspecting Python's `threading` library here, in windows not all features of threading are currently available. http://stackoverflow.com/questions/5644912/posix-threads-vs-win32-threads

**Comment by nomelif** [comment]
Awesome with an uppercase Aw. Its great that someone is helping us!
