### ISSUE TITLE
Blender 2.80 Support

### ISSUE THREAD

**Issue by ZackMercury** [nomelif/Audionodes#22]
^

**Comment by ollpu** [comment]
This is almost done: all that's left is changing all properties to the new type annotations system, and of course bumping the version in `__init__.py`.

Changing to annotations means dropping 2.79 compatibility, but I suppose that's fine.

**Comment by ollpu** [comment]
[That's it.](https://github.com/nomelif/Audionodes/commit/325183c96e10afc4a1c0ab759b7b32537b0fc0b8)

I'll make a release of this soon<sup>TM</sup>.

**Comment by ollpu** [comment]
https://github.com/nomelif/Audionodes/releases/tag/v0.3.2

**Comment by enzyme69** [comment]
Is 2.80 version not available for Mac?

**Comment by ollpu** [comment]
@enzyme69 Not yet, I'd need access to a Mac. Thanks for the reminder.

**Comment by enzyme69** [comment]
Thanks looking forward for 2.80 release on Mac

I am making another video using Blender 2.79 still only the basic, but is there tutorial on MIDI?
https://youtu.be/yQXKZs10uKY

**Comment by ollpu** [comment]
That's really nice! MIDI should be a lot easier to use in the newer versions, but as mentioned, those are not available for macOS yet. But even in 0.3, it should be plug&play, does it appear on the MIDI port manager in the Mac's settings once you create a MIDI input node?

**Comment by enzyme69** [comment]
Ok so today I am trying the MIDI setup using TouchOSC and it's MIDI bridge app, and indeed on MacBookPro, I can see the network and can route out to AudioNodes!  

<img width="1122" alt="Screen Shot 2019-11-15 at 9 10 23 pm" src="https://user-images.githubusercontent.com/3952687/68935208-59e3d080-07ec-11ea-85cc-e18b1490a07c.png">

I am using Blender 2.79 here, but do looking forward for 2.80 Mac version.

Also very curious on MIDI output if I could actually monitor the value to control animation in realtime ... I am also looking at another addon M.O.M which was AddOSC.

**Comment by enzyme69** [comment]
MOM latest update for 2.80:
http://www.jpfep.net/pages/addons/midi-osc-and-more/

**Comment by ollpu** [comment]
@enzyme69 I've added a macOS [zip for the newest version](https://github.com/nomelif/Audionodes/releases/download/v0.3.2/Audionodes-macOS.zip). Unfortunately I couldn't get the MIDI endpoint to show up in settings when quickly testing. Can you try it?

**Comment by enzyme69** [comment]
I am using 2.81 and getting this error...

```
Modules Installed (Audionodes) from '/Users/jimmygunawan/Downloads/Audionodes.zip' into '/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/Audionodes/__init__.py", line 32, in <module>
    from . import blender
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/Audionodes/blender/__init__.py", line 1, in <module>
    from . import ffi
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/Audionodes/blender/ffi.py", line 38, in <module>
    native = ct.CDLL(native_path, mode=0)
  File "/Applications/Blender.app/Contents/Resources/2.81/python/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/Audionodes/libnative.dylib, 2): Library not loaded: /usr/local/opt/fluid-synth/lib/libfluidsynth.2.dylib
  Referenced from: /Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/Audionodes/libnative.dylib
  Reason: image not found

```

**Comment by enzyme69** [comment]
@ollpu Ok seems to load fine now and testing the MIDI setup 💃  This is awesome!!
https://youtu.be/QBVTDjeSlfI
