### ISSUE TITLE
Adding a GitHub-friendly license

### ISSUE THREAD

**Issue by mozi-h** [nomelif/Audionodes#26]
Ahoy,

I just stumbled into your repo over here and noticed the license information in the `README.md`, but a missing `LICENSE.md`.

You can add a GitHub-friendly license by pressing `Create new file`, naming it `LICENSE` (`.md` optional). A button `Choose a license template` will appear to the right and allow you to select one (you seem to like GPLv3).
This will have the benefit of GitHub showing the licensing in a summary-note (x commits, x branches, x releases, ...) and other automated programs to see what you use. However, it's completely optional and a small thing, really.

Have fun coding! 

[GitHub's page about this](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository)

**Comment by ollpu** [comment]
Well aware. This has been pretty low priority I guess (procrastination at its finest).
Anyways, thanks, I'll do it now.
