### ISSUE TITLE
Any idea of sound that might sound like Tibetan Bowl or Hand Pan

### ISSUE THREAD

**Issue by enzyme69** [nomelif/Audionodes#27]
I would like to make synth sound using Audio Nodes that sounds like bell or metal or handpan Tibetan Bowl, what would be the simplest one? 

I tried:

<img width="657" alt="Screen Shot 2020-07-06 at 12 36 53 pm" src="https://user-images.githubusercontent.com/3952687/86550298-638d9480-bf85-11ea-9c6b-64336c69c7a3.png">

**Comment by ollpu** [comment]
Might be challenging, anything other than strings (simple harmonic series) can get pretty hard to synthesize. I'll try this soon.

**Comment by ollpu** [comment]
Right, a simple bell can sound quite good with frequency modulation:

![image](https://user-images.githubusercontent.com/7241014/86836843-c62a8180-c0a6-11ea-84c6-af0e540bc4f3.png)

(the parameter UI on the trigger envelope is really bad, I need to rethink it)

You could play around with longer decays (more negative decay slope) and smaller frequencies (the modulator's frequency should in general be a multiple of the main frequency) to get something closer to a tibetan bowl.

I think a lot of the characteristic sound in handpans comes from the fact that the different tones are just different base notes with similar formants (or frequency "filtering"). The interactions between the areas also get quite complex. Not sure how to approach that.

**Comment by enzyme69** [comment]
I made a YouTube video using this setup, thanks for example on using CLOCK node! Very handy~
https://youtu.be/hbiIdudCwBM

I use PushToTalk addon to record the audio.
