### ISSUE TITLE
Ubuntu 20.04 and libfluidsynth1 dependency

### ISSUE THREAD

**Issue by meikasahara** [nomelif/Audionodes#29]
Since libfluidsynth1 has been replaced by libfluidsynth2 in Ubuntu 20.04, Blender throws the error
  OSError: libfluidsynth.so.1: cannot open shared object file: No such file or directory
Are there any plans to include support for libfluidsynth2 or is there some workaround? Thanks!

**Comment by ollpu** [comment]
Thanks for the reminder (I added [support for it](https://github.com/nomelif/Audionodes/commit/9a192e017df82808def26cee2517db1b5ade5183) a while ago).

I've made a new release that links against Fluidsynth 2.
