### ISSUE TITLE
SV Hit Collision To Trigger Sound and potentially baking / output it

### ISSUE THREAD

**Issue by enzyme69** [nomelif/Audionodes#31]
I am currently WIP trying to setup collision true or false that trigger sounds once / while still colliding.

Is this "Trigger Envelope" best node to do this? Does Audio Nodes have "Value" node that simply store value so that I could change the value via SV or Animation Nodes?

<img width="580" alt="Screen Shot 2020-12-08 at 8 44 34 pm" src="https://user-images.githubusercontent.com/3952687/101467255-2eeb9200-3996-11eb-8986-9c9f738f57a8.png">

**Comment by ollpu** [comment]
Trigger signals are for events like pressing the trigger button on the socket. For a constant value you might just want to have an add node with x + 0.

**Comment by enzyme69** [comment]
Ok thanks, this is probably related to https://github.com/nomelif/Audionodes/issues/30
