### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by C-Roman** [nomelif/Audionodes#36]
Hey there! Tried to install and got this:
<img width="788" alt="Screen Shot 2021-11-08 at 10 54 00 PM" src="https://user-images.githubusercontent.com/93970275/140878803-01111147-1ec1-4f49-a554-0641fc83ec8f.png">

I have no idea what I'm doing but this looks like a really fun add-on and I'm excited to try it out!

**Comment by ollpu** [comment]
Could you paste the whole line that gets cut off at "Library not lo..."? If you can't see it otherwise, try to run Blender from the terminal.

**Comment by C-Roman** [comment]
`OSError: dlopen(/Users/ChristiahnRoman/Library/Application Support/Blender/2.93/scripts/addons/Audionodes/libnative.dylib, 2): Library not loaded: /usr/local/opt/fluid-synth/lib/libfluidsynth.2.dylib`

**Comment by ollpu** [comment]
Seems like fluidsynth has had an incompatible update recently. Assuming you already installed it with Homebrew, try the new [v0.3.4](https://github.com/nomelif/Audionodes/releases/tag/v0.3.4) release where it should be updated.

**Comment by C-Roman** [comment]
okay, cool - that worked! Thanks!
