### ISSUE TITLE
feedback / advice

### ISSUE THREAD

**Issue by zeffii** [nomelif/Audionodes#5]
Give your add a package structure early on.
```
AudioNodes/__init__.py
          /nodes/operators/op1.py  (each operator in an individual file)
          /nodes/operators/op_collection.py  (or all in a single file if they're defined succinctly)
          /nodes/generators/sine.py
          /nodes/generators/saw.py
          /nodes/generators/waveforms.py  (or all in a single file if they're defined succinctly)
          /../..
```

While the project is still light weight. i'll clone/implement an alternative structure. Ofcourse I don't expect you to accept a pullrequest of this nature, but it might be food for thought.

**Comment by zeffii** [comment]
use the node function `draw_label(self)`  if you want dynamic labels

```python

def draw_label(self):
    return <some string>
```
like we use here in Sverchok.
![image draw_label](https://cloud.githubusercontent.com/assets/619340/20650552/9e432c1a-b4d1-11e6-8e1f-cfa303692416.png)

**Comment by zeffii** [comment]
Also... pick a licence.

**Comment by nomelif** [comment]
Yes, we should set up the thing to be a folder instead of a single .py file. I agree with that.

Draw label didn't seem necessary yet. I thought about it, but couldn't come up with anything meaningful to display.

And we were thinking (to my understanding) GPL3. I will have to still discuss this with Olppu.

**Comment by zeffii** [comment]
That's up to you (license) 

until you decide I will keep my changes offline :)

**Comment by nomelif** [comment]
Ok, GPL3 it is.

**Comment by zeffii** [comment]
slightly restructured and it might interest you 

https://github.com/zeffii/audio_nodes/tree/restruct_b

**Comment by nomelif** [comment]
For me that looks great, I will consult with Olppu and maybe test that before merging it. Right now I have a ton of homework.

PS: The Win10 stuff eats VMs for breakfast.
PPS: Some Sverchok dev commented that one should separate the logic from the nodes. What was meant by that?
PPS: What does the `u` in `ugen_operators.py` stand for?

**Comment by zeffii** [comment]
unit generator,  classically in electronic sound creation this is what they are called.. since max matthews.. 
https://en.wikipedia.org/wiki/Unit_generator

**Comment by zeffii** [comment]
technically the osc's are ugens too, just specialized.

**Comment by nomelif** [comment]
Ok, makes sense.

**Comment by zeffii** [comment]
separating logic from the nodes: that was either @ly29 or me,

The optimal use of the node tree (we think) is to generate a Directed Acyclic Graph that describes how the nodes interconnect. Just the visual representation of the graph. Right now Audionodes and Sverchok both have the code inside each node, but for a variety of reasons it would make sense to implement those processes elsewhere / maybe in a different faster programming language / or even on a different computer.

This is one reason I was experimenting with SuperCollider, because the "supercollider language" (a textual description of the graph) compiles into instructions that are sent to a server where it is compiled and executed.

see SuperCollider architecture  http://supercollider.github.io/

**Comment by nomelif** [comment]
Definitely worth a look. Ollpu actually argued for such an architecture (sans the supercollider itself). You branch seems to import `oscillators` which isn't available. A quick search of the files seems to show that the oscillators are not defined anywhere. Did you forget to `git add` a file?

**Comment by zeffii** [comment]
yes my mistake. added now

**Comment by ollpu** [comment]
When planning, my idea was to construct an abstract graph of the node tree and then process it in topological order, similarly to how you explained. We ended up going with a recursive pull-mechanism (this has many caveats, such as caching being mostly an afterthought) as per nomelif's plans, just to begin with. This is something we'll definitely consider.

A big part of our project's "fun", for us at least, is that the math is mostly hand-crafted, so making it use an external sound generator might be a bigger one to digest. Of course, we might have to resort to pre-made signal processing for future nodes. Another important feature is that all changes appear live. A SuperCollider export wouldn't be impossible, though. We'll see.

**Comment by zeffii** [comment]
Hi @ollpu , no this is already quite cool.  I have no intention of pushing SuperCollider (SC) here.

**Comment by ollpu** [comment]
I'm still having trouble running your branch. It seems that the `Oscillator` class is trying to be registered as a node-type, and failing because it doesn't have a `bl_label` or something. I guess it will be necessary to remove `Node` from the `Oscillator` classes inheritances and instead inherit `Node` in the final classes. This is how the `AudioTreeNode` "mix-in" class works right now.

**Comment by zeffii** [comment]
right, it does moan about that at startup..  the tree does however output sound here..

**Comment by zeffii** [comment]
i pushed a commit that adds `bl_label` to the Oscillator class, it suppresses the warning

**Comment by ollpu** [comment]
Oh, so it doesn't interfere with the rest of the registration?

**Comment by zeffii** [comment]
nope, but i added `bl_label` to the Oscillator class, perhaps higher up would be better.. like in the `AudioTreeNode` class instead..

**Comment by ollpu** [comment]
It shouldn't be registered as node-type (and therefore not require `bl_label`) if it doesn't inherit the `Node`-class. This would just mean that the `Node`-inherits would have to be placed in the final classes instead of the `Oscillator` superclass. As I mentioned, this is what the `AudioTreeNode`-class is doing.

**Comment by zeffii** [comment]
ah yes, that makes sense.
